services:
  tpv-eureka:
    build: .
    image: tpv-eureka:1.1.0
    container_name: tpv-eureka
    restart: always
    ports:
      - "8761:8761"
    networks:
      - miw

networks:
  miw:
    external: true

#> docker compose up --build -d
