services:
  tpv-eureka:
    build: .
    image: tpv-eureka:1.1.0
    restart: always
    ports:
      - "8761:8761"
    networks:
      - miw

networks:
  miw:
    external: true

#> docker network create miw
#> docker compose -f docker-compose-dev.yml up --build -d
